source 'https://rubygems.org'

gem 'rails', '4.1.2'
gem 'mysql2'
gem 'grape'
gem 'grape-rabl'
gem 'grape-jbuilder'
gem 'sass-rails', github: 'rails/sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rails-flog'
gem 'unicorn'
gem 'therubyracer'
gem 'activeadmin', github: 'gregbell/active_admin'
#gem 'polyamorous', github: 'activerecord-hackery/polyamorous'
gem 'polyamorous'
gem "formtastic", github: "justinfrench/formtastic"
gem "ransack", github: "activerecord-hackery/ransack", branch: "rails-4.1"
gem "devise", github: "plataformatec/devise"


group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem "pry-rails"
  gem "pry-doc"
  gem 'rubocop'
  gem 'capistrano', '~> 3.2.1'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano3-unicorn'
end

group :development do
  gem 'growl', '1.0.3', :require => false
  gem 'guard-rspec'
  gem 'spring'
  gem 'quiet_assets'
  gem 'thin'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'i18n_generators'
  gem 'colorize_unpermitted_parameters'
end

group :test do
  gem 'ci_reporter'
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
  gem 'shoulda-matchers'
  gem 'fuubar'
  gem 'database_cleaner'
  gem 'rspec_junit_formatter'
  gem 'poltergeist'
  gem 'faker'
  gem "autodoc"
end
